CREATE TABLE SUBSCRIPTION_TENURE (SUBSCRIPTION_TENURE_ID INT PRIMARY KEY,SUBSCRIPTION_TENURE_PERIOD INT,SUBSCRIPTION_TENURE_DESCRIPTION NVARCHAR(100))

CREATE TABLE SIGNUP_STATUS (SIGNUP_STATUS_ID INT PRIMARY KEY,SIGNUP_STATUS_DESCRIPTION NVARCHAR(100))

CREATE TABLE HOTELS (HOTEL_ID INT PRIMARY KEY,HOTEL_NAME NVARCHAR(100),HOTEL_ADDRESS NVARCHAR(1000))

CREATE TABLE SIGNUP (NAME NVARCHAR(50),MOBILE NVARCHAR(50),EMAIL NVARCHAR(50),
                                     PASSWORD NVARCHAR(1000),SUBSCRIPTION_TENURE_ID REFERENCES SUBSCRIPTION_TENURE(SUBSCRIPTION_TENURE_ID) ,
                                     HOTEL_ID REFERENCES HOTELS(HOTEL_ID) , SIGNUP_STATUS_ID REFERENCES SIGNUP_STATUS(SIGNUP_STATUS_ID))
									 
									 
INSERT INTO SIGNUP_STATUS VALUES(100,'Approved')
INSERT INTO SIGNUP_STATUS VALUES(101,'Pending')
INSERT INTO SIGNUP_STATUS VALUES(102,'Denied')

insert into HOTELS VALUES (001,'DEFAULT','DEFAULT')


INSERT INTO SUBSCRIPTION_TENURE VALUES(001,1,'1 Year Subscription')
INSERT INTO SUBSCRIPTION_TENURE VALUES(002,0.5,'6 Months Subscription')
INSERT INTO SUBSCRIPTION_TENURE VALUES(003,0.25,'6 Months Subscription')
